blank_issues_enabled: false
contact_links:
  - name: duoduohe TanStack Community Support
    url: https://duoduohe.com
    about: Please ask and answer questions here.
  - name: duoduohe TanStack Documentation
    url: https://duoduohe.com
    about: Please check out the documentation here.
