type PaymentProvider = 'stripe' | 'creem' | 'waffo' | '';

const env = import.meta.env;

/**
 * Lightweight public env values for client-shipped code.
 *
 * Keep validation in env/client.ts for build/server checks, but avoid importing
 * @t3-oss/env-core + zod into the marketing client bundle.
 */
export const publicEnv = {
  VITE_BASE_URL: env.VITE_BASE_URL ?? 'http://localhost:3000',

  VITE_PAYMENT_PROVIDER: (env.VITE_PAYMENT_PROVIDER ?? '') as PaymentProvider,
  VITE_STRIPE_PRICE_PRO_MONTHLY: env.VITE_STRIPE_PRICE_PRO_MONTHLY,
  VITE_STRIPE_PRICE_PRO_YEARLY: env.VITE_STRIPE_PRICE_PRO_YEARLY,
  VITE_STRIPE_PRICE_LIFETIME: env.VITE_STRIPE_PRICE_LIFETIME,
  VITE_CREEM_PRODUCT_PRO_MONTHLY: env.VITE_CREEM_PRODUCT_PRO_MONTHLY,
  VITE_CREEM_PRODUCT_PRO_YEARLY: env.VITE_CREEM_PRODUCT_PRO_YEARLY,
  VITE_CREEM_PRODUCT_LIFETIME: env.VITE_CREEM_PRODUCT_LIFETIME,
  VITE_WAFFO_PRODUCT_PRO_MONTHLY: env.VITE_WAFFO_PRODUCT_PRO_MONTHLY,
  VITE_WAFFO_PRODUCT_STUDIO_MONTHLY: env.VITE_WAFFO_PRODUCT_STUDIO_MONTHLY,
  VITE_WAFFO_PRODUCT_LAUNCH_PACK: env.VITE_WAFFO_PRODUCT_LAUNCH_PACK,
  VITE_WAFFO_PRODUCT_MAKER_PACK: env.VITE_WAFFO_PRODUCT_MAKER_PACK,
  VITE_WAFFO_PRODUCT_STUDIO_PACK: env.VITE_WAFFO_PRODUCT_STUDIO_PACK,
  VITE_TURNSTILE_SITE_KEY: env.VITE_TURNSTILE_SITE_KEY,
  VITE_SUPPORT_EMAIL: env.VITE_SUPPORT_EMAIL,

  VITE_GOOGLE_ANALYTICS_ID: env.VITE_GOOGLE_ANALYTICS_ID,
  VITE_CLARITY_PROJECT_ID: env.VITE_CLARITY_PROJECT_ID,
  VITE_PLAUSIBLE_SCRIPT: env.VITE_PLAUSIBLE_SCRIPT,
  VITE_UMAMI_WEBSITE_ID: env.VITE_UMAMI_WEBSITE_ID,
  VITE_UMAMI_SCRIPT: env.VITE_UMAMI_SCRIPT,

  VITE_CRISP_WEBSITE_ID: env.VITE_CRISP_WEBSITE_ID,

  VITE_AFFILIATE_AFFONSO_ID: env.VITE_AFFILIATE_AFFONSO_ID,
  VITE_AFFILIATE_PROMOTEKIT_ID: env.VITE_AFFILIATE_PROMOTEKIT_ID,
} as const;
