import { GuidePage } from '@/components/seo/guide-page';
import { seo } from '@/lib/seo';
import { createFileRoute } from '@tanstack/react-router';

const path = '/pwa-icon-sizes';
const title =
  'PWA Icon Generator: 192px, 512px & Maskable Guide | Sunburst AI';
const description =
  'Use a free PWA icon generator to create 192×192 and 512×512 manifest icons, maskable variants, favicon assets, and a web manifest from one square source image.';

export const Route = createFileRoute('/(pages)/pwa-icon-sizes')({
  head: () =>
    seo(path, {
      title,
      description,
      keywords:
        'pwa icon generator, pwa icon sizes, pwa 192 512 icons, manifest icon sizes, maskable icon generator, web app manifest icons',
    }),
  component: PwaIconSizesPage,
});

function PwaIconSizesPage() {
  return (
    <GuidePage
      eyebrow="PWA ICON SIZES"
      title="PWA Icon Generator: 192px, 512px, and Maskable Variants"
      description={description}
      updated="September 9, 2026"
      quickFacts={[
        { label: 'Install icon', value: '192 × 192 px' },
        { label: 'Large icon', value: '512 × 512 px' },
        { label: 'Purpose', value: 'any + maskable' },
        { label: 'Metadata', value: 'Web manifest' },
      ]}
      tableTitle="PWA assets generated by Sunburst AI"
      table={{
        headers: ['File', 'Size', 'Manifest purpose'],
        rows: [
          ['icon-192.png', '192 × 192 px', 'any'],
          ['icon-512.png', '512 × 512 px', 'any'],
          ['icon-192-maskable.png', '192 × 192 px', 'maskable'],
          ['icon-512-maskable.png', '512 × 512 px', 'maskable'],
        ],
      }}
      cta={{
        href: '/favicon-generator',
        label: 'Generate PWA and favicon assets for free',
        description:
          'Upload one square icon and build the exact 192px, 512px, maskable, favicon, Apple touch, and manifest package locally in your browser.',
      }}
      sections={[
        {
          title: 'Why 192px and 512px matter',
          paragraphs: [
            'Current MDN installability guidance notes that Chromium-based browsers expect a web app manifest to include 192px and 512px icons. Those two dimensions are therefore a useful baseline for an installable PWA package.',
          ],
        },
        {
          title: 'What “maskable” changes',
          paragraphs: [
            'The manifest purpose field can tell the operating system that an icon was designed with maskable safe areas in mind. The system may crop the outer region into different shapes, so essential foreground content needs enough breathing room.',
            'Sunburst AI creates separate maskable variants rather than marking the ordinary icon as maskable without changing its layout.',
          ],
        },
        {
          title: 'Minimal manifest icon entries',
          code: '{\n  "icons": [\n    { "src": "icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any" },\n    { "src": "icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any" },\n    { "src": "icon-192-maskable.png", "sizes": "192x192", "type": "image/png", "purpose": "maskable" },\n    { "src": "icon-512-maskable.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable" }\n  ]\n}',
        },
      ]}
      sources={[
        {
          href: 'https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable',
          label: 'MDN: Making PWAs installable',
        },
        {
          href: 'https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Manifest/Reference/icons',
          label: 'MDN: Web app manifest icons reference',
        },
      ]}
      related={[
        {
          href: '/favicon-sizes',
          label: 'Favicon Sizes',
          description:
            'Cover the small browser and Apple touch icon side of the same package.',
        },
        {
          href: '/favicon-generator',
          label: 'Free Favicon + PWA Generator',
          description:
            'Generate the manifest assets locally from one square icon.',
        },
        {
          href: '/app-icon-resizer',
          label: 'Free App Icon Resizer',
          description:
            'Generate additional PNG sizes outside the manifest baseline.',
        },
      ]}
    />
  );
}
