/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPaymentRouteImport } from './routes/settings/payment'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsFilesRouteImport } from './routes/settings/files'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsApikeysRouteImport } from './routes/settings/apikeys'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardCreditsRouteImport } from './routes/dashboard/credits'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminGenerationsRouteImport } from './routes/admin/generations'
import { Route as testsTestErrorRouteImport } from './routes/(tests)/test-error'
import { Route as testsTest404RouteImport } from './routes/(tests)/test-404'
import { Route as pagesXcodeAppiconsetGuideRouteImport } from './routes/(pages)/xcode-appiconset-guide'
import { Route as pagesXcodeAppiconsetGeneratorRouteImport } from './routes/(pages)/xcode-appiconset-generator'
import { Route as pagesPwaIconSizesRouteImport } from './routes/(pages)/pwa-icon-sizes'
import { Route as pagesPricingRouteImport } from './routes/(pages)/pricing'
import { Route as pagesIosAppIconSizesRouteImport } from './routes/(pages)/ios-app-icon-sizes'
import { Route as pagesIosAppIconGeneratorRouteImport } from './routes/(pages)/ios-app-icon-generator'
import { Route as pagesGuidesRouteImport } from './routes/(pages)/guides'
import { Route as pagesFaviconSizesRouteImport } from './routes/(pages)/favicon-sizes'
import { Route as pagesFaviconGeneratorRouteImport } from './routes/(pages)/favicon-generator'
import { Route as pagesAppIconResizerRouteImport } from './routes/(pages)/app-icon-resizer'
import { Route as pagesAndroidMipmapGeneratorRouteImport } from './routes/(pages)/android-mipmap-generator'
import { Route as pagesAndroidAppIconSizesRouteImport } from './routes/(pages)/android-app-icon-sizes'
import { Route as pagesAndroidAppIconGeneratorRouteImport } from './routes/(pages)/android-app-icon-generator'
import { Route as pagesAndroidAdaptiveIconSafeZoneRouteImport } from './routes/(pages)/android-adaptive-icon-safe-zone'
import { Route as legalsTermsRouteImport } from './routes/(legals)/terms'
import { Route as legalsPrivacyRouteImport } from './routes/(legals)/privacy'
import { Route as legalsCookieRouteImport } from './routes/(legals)/cookie'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects/$projectId'
import { Route as ApiWebhooksWaffoRouteImport } from './routes/api/webhooks/waffo'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksCreemRouteImport } from './routes/api/webhooks/creem'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as ApiExportsExportIdRouteImport } from './routes/api/exports/$exportId'
import { Route as ApiE2eUsersRouteImport } from './routes/api/e2e/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as pagesModelsSunburstVsFlareRouteImport } from './routes/(pages)/models/sunburst-vs-flare'
import { Route as pagesModelsGptImage25SunburstAppIconGeneratorRouteImport } from './routes/(pages)/models/gpt-image-2-5-sunburst-app-icon-generator'
import { Route as pagesModelsGptImage25SunburstRouteImport } from './routes/(pages)/models/gpt-image-2-5-sunburst'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentRoute = SettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFilesRoute = SettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApikeysRoute = SettingsApikeysRouteImport.update({
  id: '/apikeys',
  path: '/apikeys',
  getParentRoute: () => SettingsRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreditsRoute = DashboardCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenerationsRoute = AdminGenerationsRouteImport.update({
  id: '/generations',
  path: '/generations',
  getParentRoute: () => AdminRoute,
} as any)
const testsTestErrorRoute = testsTestErrorRouteImport.update({
  id: '/(tests)/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const testsTest404Route = testsTest404RouteImport.update({
  id: '/(tests)/test-404',
  path: '/test-404',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesXcodeAppiconsetGuideRoute =
  pagesXcodeAppiconsetGuideRouteImport.update({
    id: '/(pages)/xcode-appiconset-guide',
    path: '/xcode-appiconset-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const pagesXcodeAppiconsetGeneratorRoute =
  pagesXcodeAppiconsetGeneratorRouteImport.update({
    id: '/(pages)/xcode-appiconset-generator',
    path: '/xcode-appiconset-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const pagesPwaIconSizesRoute = pagesPwaIconSizesRouteImport.update({
  id: '/(pages)/pwa-icon-sizes',
  path: '/pwa-icon-sizes',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesPricingRoute = pagesPricingRouteImport.update({
  id: '/(pages)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesIosAppIconSizesRoute = pagesIosAppIconSizesRouteImport.update({
  id: '/(pages)/ios-app-icon-sizes',
  path: '/ios-app-icon-sizes',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesIosAppIconGeneratorRoute =
  pagesIosAppIconGeneratorRouteImport.update({
    id: '/(pages)/ios-app-icon-generator',
    path: '/ios-app-icon-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const pagesGuidesRoute = pagesGuidesRouteImport.update({
  id: '/(pages)/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesFaviconSizesRoute = pagesFaviconSizesRouteImport.update({
  id: '/(pages)/favicon-sizes',
  path: '/favicon-sizes',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesFaviconGeneratorRoute = pagesFaviconGeneratorRouteImport.update({
  id: '/(pages)/favicon-generator',
  path: '/favicon-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAppIconResizerRoute = pagesAppIconResizerRouteImport.update({
  id: '/(pages)/app-icon-resizer',
  path: '/app-icon-resizer',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAndroidMipmapGeneratorRoute =
  pagesAndroidMipmapGeneratorRouteImport.update({
    id: '/(pages)/android-mipmap-generator',
    path: '/android-mipmap-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const pagesAndroidAppIconSizesRoute =
  pagesAndroidAppIconSizesRouteImport.update({
    id: '/(pages)/android-app-icon-sizes',
    path: '/android-app-icon-sizes',
    getParentRoute: () => rootRouteImport,
  } as any)
const pagesAndroidAppIconGeneratorRoute =
  pagesAndroidAppIconGeneratorRouteImport.update({
    id: '/(pages)/android-app-icon-generator',
    path: '/android-app-icon-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const pagesAndroidAdaptiveIconSafeZoneRoute =
  pagesAndroidAdaptiveIconSafeZoneRouteImport.update({
    id: '/(pages)/android-adaptive-icon-safe-zone',
    path: '/android-adaptive-icon-safe-zone',
    getParentRoute: () => rootRouteImport,
  } as any)
const legalsTermsRoute = legalsTermsRouteImport.update({
  id: '/(legals)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsPrivacyRoute = legalsPrivacyRouteImport.update({
  id: '/(legals)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsCookieRoute = legalsCookieRouteImport.update({
  id: '/(legals)/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiWebhooksWaffoRoute = ApiWebhooksWaffoRouteImport.update({
  id: '/api/webhooks/waffo',
  path: '/api/webhooks/waffo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCreemRoute = ApiWebhooksCreemRouteImport.update({
  id: '/api/webhooks/creem',
  path: '/api/webhooks/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportsExportIdRoute = ApiExportsExportIdRouteImport.update({
  id: '/api/exports/$exportId',
  path: '/api/exports/$exportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eUsersRoute = ApiE2eUsersRouteImport.update({
  id: '/api/e2e/users',
  path: '/api/e2e/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesModelsSunburstVsFlareRoute =
  pagesModelsSunburstVsFlareRouteImport.update({
    id: '/(pages)/models/sunburst-vs-flare',
    path: '/models/sunburst-vs-flare',
    getParentRoute: () => rootRouteImport,
  } as any)
const pagesModelsGptImage25SunburstAppIconGeneratorRoute =
  pagesModelsGptImage25SunburstAppIconGeneratorRouteImport.update({
    id: '/(pages)/models/gpt-image-2-5-sunburst-app-icon-generator',
    path: '/models/gpt-image-2-5-sunburst-app-icon-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const pagesModelsGptImage25SunburstRoute =
  pagesModelsGptImage25SunburstRouteImport.update({
    id: '/(pages)/models/gpt-image-2-5-sunburst',
    path: '/models/gpt-image-2-5-sunburst',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/generate': typeof GenerateRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/android-adaptive-icon-safe-zone': typeof pagesAndroidAdaptiveIconSafeZoneRoute
  '/android-app-icon-generator': typeof pagesAndroidAppIconGeneratorRoute
  '/android-app-icon-sizes': typeof pagesAndroidAppIconSizesRoute
  '/android-mipmap-generator': typeof pagesAndroidMipmapGeneratorRoute
  '/app-icon-resizer': typeof pagesAppIconResizerRoute
  '/favicon-generator': typeof pagesFaviconGeneratorRoute
  '/favicon-sizes': typeof pagesFaviconSizesRoute
  '/guides': typeof pagesGuidesRoute
  '/ios-app-icon-generator': typeof pagesIosAppIconGeneratorRoute
  '/ios-app-icon-sizes': typeof pagesIosAppIconSizesRoute
  '/pricing': typeof pagesPricingRoute
  '/pwa-icon-sizes': typeof pagesPwaIconSizesRoute
  '/xcode-appiconset-generator': typeof pagesXcodeAppiconsetGeneratorRoute
  '/xcode-appiconset-guide': typeof pagesXcodeAppiconsetGuideRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/generations': typeof AdminGenerationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/models/gpt-image-2-5-sunburst': typeof pagesModelsGptImage25SunburstRoute
  '/models/gpt-image-2-5-sunburst-app-icon-generator': typeof pagesModelsGptImage25SunburstAppIconGeneratorRoute
  '/models/sunburst-vs-flare': typeof pagesModelsSunburstVsFlareRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/exports/$exportId': typeof ApiExportsExportIdRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/waffo': typeof ApiWebhooksWaffoRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/generate': typeof GenerateRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/android-adaptive-icon-safe-zone': typeof pagesAndroidAdaptiveIconSafeZoneRoute
  '/android-app-icon-generator': typeof pagesAndroidAppIconGeneratorRoute
  '/android-app-icon-sizes': typeof pagesAndroidAppIconSizesRoute
  '/android-mipmap-generator': typeof pagesAndroidMipmapGeneratorRoute
  '/app-icon-resizer': typeof pagesAppIconResizerRoute
  '/favicon-generator': typeof pagesFaviconGeneratorRoute
  '/favicon-sizes': typeof pagesFaviconSizesRoute
  '/guides': typeof pagesGuidesRoute
  '/ios-app-icon-generator': typeof pagesIosAppIconGeneratorRoute
  '/ios-app-icon-sizes': typeof pagesIosAppIconSizesRoute
  '/pricing': typeof pagesPricingRoute
  '/pwa-icon-sizes': typeof pagesPwaIconSizesRoute
  '/xcode-appiconset-generator': typeof pagesXcodeAppiconsetGeneratorRoute
  '/xcode-appiconset-guide': typeof pagesXcodeAppiconsetGuideRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/generations': typeof AdminGenerationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/models/gpt-image-2-5-sunburst': typeof pagesModelsGptImage25SunburstRoute
  '/models/gpt-image-2-5-sunburst-app-icon-generator': typeof pagesModelsGptImage25SunburstAppIconGeneratorRoute
  '/models/sunburst-vs-flare': typeof pagesModelsSunburstVsFlareRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/exports/$exportId': typeof ApiExportsExportIdRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/waffo': typeof ApiWebhooksWaffoRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/generate': typeof GenerateRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(legals)/cookie': typeof legalsCookieRoute
  '/(legals)/privacy': typeof legalsPrivacyRoute
  '/(legals)/terms': typeof legalsTermsRoute
  '/(pages)/android-adaptive-icon-safe-zone': typeof pagesAndroidAdaptiveIconSafeZoneRoute
  '/(pages)/android-app-icon-generator': typeof pagesAndroidAppIconGeneratorRoute
  '/(pages)/android-app-icon-sizes': typeof pagesAndroidAppIconSizesRoute
  '/(pages)/android-mipmap-generator': typeof pagesAndroidMipmapGeneratorRoute
  '/(pages)/app-icon-resizer': typeof pagesAppIconResizerRoute
  '/(pages)/favicon-generator': typeof pagesFaviconGeneratorRoute
  '/(pages)/favicon-sizes': typeof pagesFaviconSizesRoute
  '/(pages)/guides': typeof pagesGuidesRoute
  '/(pages)/ios-app-icon-generator': typeof pagesIosAppIconGeneratorRoute
  '/(pages)/ios-app-icon-sizes': typeof pagesIosAppIconSizesRoute
  '/(pages)/pricing': typeof pagesPricingRoute
  '/(pages)/pwa-icon-sizes': typeof pagesPwaIconSizesRoute
  '/(pages)/xcode-appiconset-generator': typeof pagesXcodeAppiconsetGeneratorRoute
  '/(pages)/xcode-appiconset-guide': typeof pagesXcodeAppiconsetGuideRoute
  '/(tests)/test-404': typeof testsTest404Route
  '/(tests)/test-error': typeof testsTestErrorRoute
  '/admin/generations': typeof AdminGenerationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/(pages)/models/gpt-image-2-5-sunburst': typeof pagesModelsGptImage25SunburstRoute
  '/(pages)/models/gpt-image-2-5-sunburst-app-icon-generator': typeof pagesModelsGptImage25SunburstAppIconGeneratorRoute
  '/(pages)/models/sunburst-vs-flare': typeof pagesModelsSunburstVsFlareRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/exports/$exportId': typeof ApiExportsExportIdRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/waffo': typeof ApiWebhooksWaffoRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/generate'
    | '/manifest.json'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/android-adaptive-icon-safe-zone'
    | '/android-app-icon-generator'
    | '/android-app-icon-sizes'
    | '/android-mipmap-generator'
    | '/app-icon-resizer'
    | '/favicon-generator'
    | '/favicon-sizes'
    | '/guides'
    | '/ios-app-icon-generator'
    | '/ios-app-icon-sizes'
    | '/pricing'
    | '/pwa-icon-sizes'
    | '/xcode-appiconset-generator'
    | '/xcode-appiconset-guide'
    | '/test-404'
    | '/test-error'
    | '/admin/generations'
    | '/admin/orders'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/credits'
    | '/dashboard/history'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/dashboard/'
    | '/settings/'
    | '/models/gpt-image-2-5-sunburst'
    | '/models/gpt-image-2-5-sunburst-app-icon-generator'
    | '/models/sunburst-vs-flare'
    | '/api/auth/$'
    | '/api/e2e/users'
    | '/api/exports/$exportId'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/api/webhooks/waffo'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/generate'
    | '/manifest.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/android-adaptive-icon-safe-zone'
    | '/android-app-icon-generator'
    | '/android-app-icon-sizes'
    | '/android-mipmap-generator'
    | '/app-icon-resizer'
    | '/favicon-generator'
    | '/favicon-sizes'
    | '/guides'
    | '/ios-app-icon-generator'
    | '/ios-app-icon-sizes'
    | '/pricing'
    | '/pwa-icon-sizes'
    | '/xcode-appiconset-generator'
    | '/xcode-appiconset-guide'
    | '/test-404'
    | '/test-error'
    | '/admin/generations'
    | '/admin/orders'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/credits'
    | '/dashboard/history'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/models/gpt-image-2-5-sunburst'
    | '/models/gpt-image-2-5-sunburst-app-icon-generator'
    | '/models/sunburst-vs-flare'
    | '/api/auth/$'
    | '/api/e2e/users'
    | '/api/exports/$exportId'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/api/webhooks/waffo'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/generate'
    | '/manifest.json'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/(legals)/cookie'
    | '/(legals)/privacy'
    | '/(legals)/terms'
    | '/(pages)/android-adaptive-icon-safe-zone'
    | '/(pages)/android-app-icon-generator'
    | '/(pages)/android-app-icon-sizes'
    | '/(pages)/android-mipmap-generator'
    | '/(pages)/app-icon-resizer'
    | '/(pages)/favicon-generator'
    | '/(pages)/favicon-sizes'
    | '/(pages)/guides'
    | '/(pages)/ios-app-icon-generator'
    | '/(pages)/ios-app-icon-sizes'
    | '/(pages)/pricing'
    | '/(pages)/pwa-icon-sizes'
    | '/(pages)/xcode-appiconset-generator'
    | '/(pages)/xcode-appiconset-guide'
    | '/(tests)/test-404'
    | '/(tests)/test-error'
    | '/admin/generations'
    | '/admin/orders'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/credits'
    | '/dashboard/history'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/dashboard/'
    | '/settings/'
    | '/(pages)/models/gpt-image-2-5-sunburst'
    | '/(pages)/models/gpt-image-2-5-sunburst-app-icon-generator'
    | '/(pages)/models/sunburst-vs-flare'
    | '/api/auth/$'
    | '/api/e2e/users'
    | '/api/exports/$exportId'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/api/webhooks/waffo'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  GenerateRoute: typeof GenerateRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  legalsCookieRoute: typeof legalsCookieRoute
  legalsPrivacyRoute: typeof legalsPrivacyRoute
  legalsTermsRoute: typeof legalsTermsRoute
  pagesAndroidAdaptiveIconSafeZoneRoute: typeof pagesAndroidAdaptiveIconSafeZoneRoute
  pagesAndroidAppIconGeneratorRoute: typeof pagesAndroidAppIconGeneratorRoute
  pagesAndroidAppIconSizesRoute: typeof pagesAndroidAppIconSizesRoute
  pagesAndroidMipmapGeneratorRoute: typeof pagesAndroidMipmapGeneratorRoute
  pagesAppIconResizerRoute: typeof pagesAppIconResizerRoute
  pagesFaviconGeneratorRoute: typeof pagesFaviconGeneratorRoute
  pagesFaviconSizesRoute: typeof pagesFaviconSizesRoute
  pagesGuidesRoute: typeof pagesGuidesRoute
  pagesIosAppIconGeneratorRoute: typeof pagesIosAppIconGeneratorRoute
  pagesIosAppIconSizesRoute: typeof pagesIosAppIconSizesRoute
  pagesPricingRoute: typeof pagesPricingRoute
  pagesPwaIconSizesRoute: typeof pagesPwaIconSizesRoute
  pagesXcodeAppiconsetGeneratorRoute: typeof pagesXcodeAppiconsetGeneratorRoute
  pagesXcodeAppiconsetGuideRoute: typeof pagesXcodeAppiconsetGuideRoute
  testsTest404Route: typeof testsTest404Route
  testsTestErrorRoute: typeof testsTestErrorRoute
  ApiPingRoute: typeof ApiPingRoute
  pagesModelsGptImage25SunburstRoute: typeof pagesModelsGptImage25SunburstRoute
  pagesModelsGptImage25SunburstAppIconGeneratorRoute: typeof pagesModelsGptImage25SunburstAppIconGeneratorRoute
  pagesModelsSunburstVsFlareRoute: typeof pagesModelsSunburstVsFlareRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiE2eUsersRoute: typeof ApiE2eUsersRoute
  ApiExportsExportIdRoute: typeof ApiExportsExportIdRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiWebhooksCreemRoute: typeof ApiWebhooksCreemRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiWebhooksWaffoRoute: typeof ApiWebhooksWaffoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payment': {
      id: '/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsPaymentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/files': {
      id: '/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof SettingsFilesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/apikeys': {
      id: '/settings/apikeys'
      path: '/apikeys'
      fullPath: '/settings/apikeys'
      preLoaderRoute: typeof SettingsApikeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/credits': {
      id: '/dashboard/credits'
      path: '/credits'
      fullPath: '/dashboard/credits'
      preLoaderRoute: typeof DashboardCreditsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generations': {
      id: '/admin/generations'
      path: '/generations'
      fullPath: '/admin/generations'
      preLoaderRoute: typeof AdminGenerationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(tests)/test-error': {
      id: '/(tests)/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof testsTestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/test-404': {
      id: '/(tests)/test-404'
      path: '/test-404'
      fullPath: '/test-404'
      preLoaderRoute: typeof testsTest404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/xcode-appiconset-guide': {
      id: '/(pages)/xcode-appiconset-guide'
      path: '/xcode-appiconset-guide'
      fullPath: '/xcode-appiconset-guide'
      preLoaderRoute: typeof pagesXcodeAppiconsetGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/xcode-appiconset-generator': {
      id: '/(pages)/xcode-appiconset-generator'
      path: '/xcode-appiconset-generator'
      fullPath: '/xcode-appiconset-generator'
      preLoaderRoute: typeof pagesXcodeAppiconsetGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/pwa-icon-sizes': {
      id: '/(pages)/pwa-icon-sizes'
      path: '/pwa-icon-sizes'
      fullPath: '/pwa-icon-sizes'
      preLoaderRoute: typeof pagesPwaIconSizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/pricing': {
      id: '/(pages)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof pagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/ios-app-icon-sizes': {
      id: '/(pages)/ios-app-icon-sizes'
      path: '/ios-app-icon-sizes'
      fullPath: '/ios-app-icon-sizes'
      preLoaderRoute: typeof pagesIosAppIconSizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/ios-app-icon-generator': {
      id: '/(pages)/ios-app-icon-generator'
      path: '/ios-app-icon-generator'
      fullPath: '/ios-app-icon-generator'
      preLoaderRoute: typeof pagesIosAppIconGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/guides': {
      id: '/(pages)/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof pagesGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/favicon-sizes': {
      id: '/(pages)/favicon-sizes'
      path: '/favicon-sizes'
      fullPath: '/favicon-sizes'
      preLoaderRoute: typeof pagesFaviconSizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/favicon-generator': {
      id: '/(pages)/favicon-generator'
      path: '/favicon-generator'
      fullPath: '/favicon-generator'
      preLoaderRoute: typeof pagesFaviconGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/app-icon-resizer': {
      id: '/(pages)/app-icon-resizer'
      path: '/app-icon-resizer'
      fullPath: '/app-icon-resizer'
      preLoaderRoute: typeof pagesAppIconResizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/android-mipmap-generator': {
      id: '/(pages)/android-mipmap-generator'
      path: '/android-mipmap-generator'
      fullPath: '/android-mipmap-generator'
      preLoaderRoute: typeof pagesAndroidMipmapGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/android-app-icon-sizes': {
      id: '/(pages)/android-app-icon-sizes'
      path: '/android-app-icon-sizes'
      fullPath: '/android-app-icon-sizes'
      preLoaderRoute: typeof pagesAndroidAppIconSizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/android-app-icon-generator': {
      id: '/(pages)/android-app-icon-generator'
      path: '/android-app-icon-generator'
      fullPath: '/android-app-icon-generator'
      preLoaderRoute: typeof pagesAndroidAppIconGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/android-adaptive-icon-safe-zone': {
      id: '/(pages)/android-adaptive-icon-safe-zone'
      path: '/android-adaptive-icon-safe-zone'
      fullPath: '/android-adaptive-icon-safe-zone'
      preLoaderRoute: typeof pagesAndroidAdaptiveIconSafeZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/terms': {
      id: '/(legals)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/privacy': {
      id: '/(legals)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/cookie': {
      id: '/(legals)/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof legalsCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhooks/waffo': {
      id: '/api/webhooks/waffo'
      path: '/api/webhooks/waffo'
      fullPath: '/api/webhooks/waffo'
      preLoaderRoute: typeof ApiWebhooksWaffoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/creem': {
      id: '/api/webhooks/creem'
      path: '/api/webhooks/creem'
      fullPath: '/api/webhooks/creem'
      preLoaderRoute: typeof ApiWebhooksCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exports/$exportId': {
      id: '/api/exports/$exportId'
      path: '/api/exports/$exportId'
      fullPath: '/api/exports/$exportId'
      preLoaderRoute: typeof ApiExportsExportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/users': {
      id: '/api/e2e/users'
      path: '/api/e2e/users'
      fullPath: '/api/e2e/users'
      preLoaderRoute: typeof ApiE2eUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/models/sunburst-vs-flare': {
      id: '/(pages)/models/sunburst-vs-flare'
      path: '/models/sunburst-vs-flare'
      fullPath: '/models/sunburst-vs-flare'
      preLoaderRoute: typeof pagesModelsSunburstVsFlareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/models/gpt-image-2-5-sunburst-app-icon-generator': {
      id: '/(pages)/models/gpt-image-2-5-sunburst-app-icon-generator'
      path: '/models/gpt-image-2-5-sunburst-app-icon-generator'
      fullPath: '/models/gpt-image-2-5-sunburst-app-icon-generator'
      preLoaderRoute: typeof pagesModelsGptImage25SunburstAppIconGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/models/gpt-image-2-5-sunburst': {
      id: '/(pages)/models/gpt-image-2-5-sunburst'
      path: '/models/gpt-image-2-5-sunburst'
      fullPath: '/models/gpt-image-2-5-sunburst'
      preLoaderRoute: typeof pagesModelsGptImage25SunburstRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGenerationsRoute: typeof AdminGenerationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGenerationsRoute: AdminGenerationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardCreditsRoute: typeof DashboardCreditsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCreditsRoute: DashboardCreditsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SettingsRouteChildren {
  SettingsApikeysRoute: typeof SettingsApikeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsFilesRoute: typeof SettingsFilesRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPaymentRoute: typeof SettingsPaymentRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApikeysRoute: SettingsApikeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsFilesRoute: SettingsFilesRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPaymentRoute: SettingsPaymentRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  GenerateRoute: GenerateRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  legalsCookieRoute: legalsCookieRoute,
  legalsPrivacyRoute: legalsPrivacyRoute,
  legalsTermsRoute: legalsTermsRoute,
  pagesAndroidAdaptiveIconSafeZoneRoute: pagesAndroidAdaptiveIconSafeZoneRoute,
  pagesAndroidAppIconGeneratorRoute: pagesAndroidAppIconGeneratorRoute,
  pagesAndroidAppIconSizesRoute: pagesAndroidAppIconSizesRoute,
  pagesAndroidMipmapGeneratorRoute: pagesAndroidMipmapGeneratorRoute,
  pagesAppIconResizerRoute: pagesAppIconResizerRoute,
  pagesFaviconGeneratorRoute: pagesFaviconGeneratorRoute,
  pagesFaviconSizesRoute: pagesFaviconSizesRoute,
  pagesGuidesRoute: pagesGuidesRoute,
  pagesIosAppIconGeneratorRoute: pagesIosAppIconGeneratorRoute,
  pagesIosAppIconSizesRoute: pagesIosAppIconSizesRoute,
  pagesPricingRoute: pagesPricingRoute,
  pagesPwaIconSizesRoute: pagesPwaIconSizesRoute,
  pagesXcodeAppiconsetGeneratorRoute: pagesXcodeAppiconsetGeneratorRoute,
  pagesXcodeAppiconsetGuideRoute: pagesXcodeAppiconsetGuideRoute,
  testsTest404Route: testsTest404Route,
  testsTestErrorRoute: testsTestErrorRoute,
  ApiPingRoute: ApiPingRoute,
  pagesModelsGptImage25SunburstRoute: pagesModelsGptImage25SunburstRoute,
  pagesModelsGptImage25SunburstAppIconGeneratorRoute:
    pagesModelsGptImage25SunburstAppIconGeneratorRoute,
  pagesModelsSunburstVsFlareRoute: pagesModelsSunburstVsFlareRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiE2eUsersRoute: ApiE2eUsersRoute,
  ApiExportsExportIdRoute: ApiExportsExportIdRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiWebhooksCreemRoute: ApiWebhooksCreemRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiWebhooksWaffoRoute: ApiWebhooksWaffoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
